name: My first workflow
on:
  push:
    branches: 
     - 'release/v[1-9].[0-9]+'
    
jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: v18.16.0

      - name: envRailway
        run: npm i -g @railway/cli

      - name: Application
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up

      - name: Send Notification
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_LINK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "SA56 CICD Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nShwe Yamin Oo"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\ne1112942@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:*\nA0269559E"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Respository:*\n${{ github.event.repository.html_url }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "https://${{ secrets.DEPLOY_LINK }}.up.railway.app/"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": true
                  },
                  "value": "click_me_123",
                  "url": "https://${{ secrets.DEPLOY_LINK }}.up.railway.app/",
                  "action_id": "button-action"
                }
              }
            ]
            }

